# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 14:15
from __future__ import unicode_literals

import os

from django.db import migrations, models
from django.conf import settings
from django.core.files import File
from django.template.defaultfilters import slugify

def seed_products(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    ProductPart = apps.get_model('products', 'ProductPart')

    DATA_DIR = os.path.join(str(settings.ROOT_DIR), 'data')
    PRODUCTS_DIR = os.path.join(str(DATA_DIR), 'products')

    sep = os.path.sep

    acrylic_products = [
        {'name': 'Okland', 'description': 'Rectangular bathtub\n180 x 90 cm with panel',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '001-Oakland' + sep +
                                    'main_img' + sep + 'Oakland-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '001-Oakland' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '001-Oakland' + sep +
                                    'main_img' + sep + 'Oakland-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Toledo', 'description': 'Right & Left angle bathtub 160 x 90 cm, available with front panel and fixing kit',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '002-Toledo' + sep +
                                    'main_img' + sep + 'Toledo-2-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '002-Toledo' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '002-Toledo' + sep +
                                    'main_img' + sep + 'Toledo-2-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Florida', 'description': 'Corner bathtub 140 x 140 cm with panel and fixing kit',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '003-Florida' + sep +
                                    'main_img' + sep + 'Florida.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '003-Florida' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '003-Florida' + sep +
                                    'main_img' + sep + 'Florida.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'California', 'description': 'Corner bathtub 140 x 140 cm with panel and fixing kit',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '004-California' + sep +
                                    'main_img' + sep + 'California.-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '004-California' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '004-California' + sep +
                                    'main_img' + sep + 'California.-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Tampa', 'description': 'Rectangular bathtub:\n170 x 75 cm\n170 x 80 cm',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '005-Tampa' + sep +
                                    'main_img' + sep + 'Tampa.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '005-Tampa' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '005-Tampa' + sep +
                                    'main_img' + sep + 'Tampa.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Dallas', 'description': 'Corner bathtub with panel and fixing kit, available sizes :\n125 x 125 cm\n110 x 110 cm',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '006-Dallas' + sep +
                                    'main_img' + sep + 'Dallas-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '006-Dallas' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '006-Dallas' + sep +
                                    'main_img' + sep + 'Dallas-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'New York', 'description': 'Corner bathtub with panel and fixing kit, available sizes :\n135 x 135 cm\n130 x 130 cm',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '007-New York' + sep +
                                    'main_img' + sep + 'New-York-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '007-New York' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '007-New York' + sep +
                                    'main_img' + sep + 'New-York-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Hawaii', 'description': 'Rectangular bathtub 180 x 80 cm with panel',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '008-Hawaii' + sep +
                                    'main_img' + sep + 'Hawaii.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '008-Hawaii' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '008-Hawaii' + sep +
                                    'main_img' + sep + 'Hawaii.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Vegas', 'description': 'Rectangular bathtub\n180 x 80 cm with panel',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '009-Vegas' + sep +
                                    'main_img' + sep + 'Vegas-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '009-Vegas' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '009-Vegas' + sep +
                                    'main_img' + sep + 'Vegas-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Pennsylvania', 'description': 'Rectangular bathtub\n170 x 70 cm with or\nwithout seat',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '010-Pennsylvania' + sep +
                                    'main_img' + sep + 'Pannsylvania.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '010-Pennsylvania' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '010-Pennsylvania' + sep +
                                    'main_img' + sep + 'Pannsylvania.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Atlanta', 'description': 'Rectangular bathtub\n180 x 90 cm with panel',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '011-Atlanta' + sep +
                                    'main_img' + sep + 'Atlanta.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '011-Atlanta' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '011-Atlanta' + sep +
                                    'main_img' + sep + 'Atlanta.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Orlando', 'description': 'Rectangular bathtub:\n140 x 70 cm\n150 x 70 cm\n160 x 70 cm\n170 x 70 cm',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '012-Orlando' + sep +
                                    'main_img' + sep + 'Orlando-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '012-Orlando' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '012-Orlando' + sep +
                                    'main_img' + sep + 'Orlando-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Nevada', 'description': 'Rectangular bathtub\n170 x 80 cm with  seat',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '013-Nevada' + sep +
                                    'main_img' + sep + 'Nevada.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '013-Nevada' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '013-Nevada' + sep +
                                    'main_img' + sep + 'Nevada.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Miami', 'description': 'Rectangular bathtub with seat :\n105 x 70 cm\n120 x 70 cm',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '014-Miami' + sep +
                                    'main_img' + sep + 'Miami-1.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '014-Miami' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '014-Miami' + sep +
                                    'main_img' + sep + 'Miami-1.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Christina', 'description': 'Rectangular bathtub: \n140 x 70 cm\n150 x 70 cm\n160 x 70 cm\n170 x 70 cm\n170 x 75 cm',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '015-Christina' + sep +
                                    'main_img' + sep + 'Christina-Set.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '015-Christina' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '015-Christina' + sep +
                                    'main_img' + sep + 'Christina-Set.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Texas', 'description': '\n',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '016-Texas' + sep +
                                    'main_img' + sep + 'Texas.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '016-Texas' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '016-Texas' + sep +
                                    'main_img' + sep + 'Texas.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Colorado', 'description': 'Corner shower tray:\n70 x 70 x 10.5 cm depth\n80 x 80 x 11cm depth\n90 x 90 x 7 cm depth',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '017-Colorado' + sep +
                                    'main_img' + sep + 'colorado.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '017-Colorado' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '017-Colorado' + sep +
                                    'main_img' + sep + 'colorado.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Boston', 'description': 'Corner shower tray: 70 x 70 x 11cm depth\n80 x 80 x 11 cm depth\n90 x 90 x 7 cm depth',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '018-Boston' + sep +
                                    'main_img' + sep + 'Boston.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '018-Boston' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '018-Boston' + sep +
                                    'main_img' + sep + 'Boston.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Indiana', 'description': 'Square shower tray:\n70 x 70 x 10.5 cm depth\n80 x 80 x 11 cm depth\n90 x 90 x 7 cm depth',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '019-Indiana' + sep +
                                    'main_img' + sep + 'Indiana.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '019-Indiana' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '019-Indiana' + sep +
                                    'main_img' + sep + 'Indiana.jpg'),
               'description': '\n'
              }
          ]
        },
        {'name': 'Houston', 'description': 'Square shower tray:\n63 x 63 x 15 cm depth\n70 x 70 x 13.5 cm depth\n80 x 80 x 14.5 cm depth\n90 x 90 x 11.5 cm depth',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '020-Houston' + sep +
                                    'main_img' + sep + 'hoston.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '020-Houston' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'ACRYLIC BATH TUBS' +
                                    sep + '020-Houston' + sep +
                                    'main_img' + sep + 'hoston.jpg'),
               'description': '\n'
              }
          ]
        },
        
    ]

    sanitary_products = [
        {'name': 'Clara', 'description': 'Clara\n\nClara, luxury and elegance that brings beauty wherever displayed.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '57 cm lavatory includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '68 cm lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '70 cm lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '05' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '05' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P"&"S" trap versions with or without integrated douche sprayer'
              },
          ]
        },
        {'name': 'Cleo', 'description': 'Lord\n\nThe Lord of space is specially fabricated with its gold like fashion, floral, or marbleized style for the vast & spacious bathroom.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '70 x 55 cm and 60 x 48 cm lavatory with floor standing pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '70 x 55cm and 60 x 48 cm lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '02 Cleo' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P"&"S" trap versions with or without integrated douche sprayer'
              }
          ]
        },
        {'name': 'Piccolo', 'description': 'Christina\nThe modern style with its 3 sized washbasins is presented to please every taste & to fit every space.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '60 cm lavatory with floor standing pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '60 cm lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P"&"S" trap versions with or without integrated douche sprayer'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '05' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '03 Piccolo' + sep + '05' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing water closet, available in "P" & "S" trap versions without integrated douche sprayer'
              },
          ]
        },
        {'name': 'Christina', 'description': 'Christina\nThe modern style with its 3 sized washbasins is presented to please every taste & to fit every space.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '63 cm lavatory with floor standing pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '\n'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole  '
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '04 Christina' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing water closet, available in "P" & "S" trap versions'
              },
          ]
        },
        {'name': 'Enigma', 'description': 'Enigma\n\nThe wall-hung set is the fashionable trend of the distinctive projects & the refined elite. A name that stands on its own.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '05 Enigma' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '01 Clara' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '05 Enigma' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '63 cm lavatory with wall pedestal includes one pre-punched & two semi-punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '05 Enigma' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '05 Enigma' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall hung bidet includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '05 Enigma' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '05 Enigma' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall hung water closet available in "P" trap version'
              },
          ]
        },
        {'name': 'Juliana', 'description': 'Juliana\nThe convenient size with its round lines makes it suitable for a “Petite” bathroom.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '55,60 cm lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '60 cm lavatory with floor standing or wall hung pedestal includes one pre-punched & two semi-punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '06 Juliana' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P"&"S" trap versions with or without integrated douche sprayer'
              },
          ]
        },
        {'name': 'Cascada', 'description': 'Cascada\n\nThe curves and size of this chic Cascada set make it a perfect elegant solution',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '07 Cascada' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '07 Cascada' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '07 Cascada' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '60 cm lavatory with floor standing pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '07 Cascada' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '07 Cascada' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet. Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '07 Cascada' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '07 Cascada' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P" trap with or without integrated douche sprayer'
              },
          ]
        },
        {'name': 'Tris', 'description': 'Tris\n\nThe most salable & convenient small set, the simple style for everyone.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '64 x 53.5 cm , 58 x 46.5 cm  lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '64 x 53.5 cm , 58 x 46.5 cm lavatory with floor standing pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P"&"S" trap versions with or without integrated douche sprayer'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '05' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '08 Tris' + sep + '05' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing water closet available in "P" & "S" trap verions'
              },
          ]
        },
        {'name': 'Magic', 'description': 'Magic\n\nThe set with its round sleek lines can turn any small space into a fantasy.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '55 cm lavatory with wall pedestal includes one pre-punched & two semi-punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '55 lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '09 Magic' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P"&"S" trap versions with or without integrated douche sprayer'
              },
          ]
        },
        {'name': 'Lord', 'description': 'Lord\n\nThe Lord of space is specially fabricated with its gold like fashion, floral, or marbleized style for the vast & spacious bathroom.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '10 Lord' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '10 Lord' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '10 Lord' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '75 cm lavatory with floor standing pedestal includes one pre-punched & two semi- punched faucet holes'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '10 Lord' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '10 Lord' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor standing bidet . Includes one punched faucet hole'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '10 Lord' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'SANITARY WARE' +
                                    sep + '10 Lord' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Floor Standing close coupled water closet available in "P"&"S" trap versions with or without integrated douche sprayer'
              },
          ]
        },
        
    ]
    wt_products = [
        {'name': 'Polo', 'description': '\n',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Single lever basin mixer'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Single lever sink mixer'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Single lever sink mixer'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Showering kit single function'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '05' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '001-Polo' + sep + '05' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': ' Single lever bidet mixer'
              },
          ]
        },
        {'name': 'Novara', 'description': '\n',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Monobloc, dual-control, swivel spout, basin mixer with ceramic disk, turn cartridges, with flexible hose, supply connections included.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Monobloc, dual-control, swivel spout, basin mixer with ceramic disk,  turn cartridges, with flexible hose, supply connections included.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall-mount, kitchen sink faucet with ceramic disk cartridges & swivel spout.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '\n'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '05' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '002-Novara' + sep + '05' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Monobloc, dual-control, bidet fitting with ceramic disk, turn cartridges, with flexible hose, supply connections included.'
              },
          ]
        },
        {'name': 'Bresica', 'description': '\n',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Monobloc , dual-control, swivel spot basin mixer'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '\n'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall-mount, kitchen sink faucet with swivel spout.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Dual-control, exposed-wall , bath / shower fitting'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '05' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '003-Bresica' + sep + '05' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Monobloc , dual-control, bidet fitting'
              },
          ]
        },
        {'name': 'Gold', 'description': '\n',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Dual-control, basin mixer, bridge type with swivel spout'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall-mount, kitchen sink faucet with swivel spout'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall-mount, kitchen sink faucet with swivel spout'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '004-Gold' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '\n'
              },
          ]
        },
        {'name': 'General Special', 'description': '\n',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Single hole basin mixer with dual-control & swivel spout.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '\n'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall-mount, kitchen sink faucet with swivel spout.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '005-General - Special' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Dual-control, exposed-wall , bath / shower fitting.'
              },
          ]
        },
        {'name': 'Crown', 'description': '\n',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep +
                                    'main_img' + sep + 'img.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '01' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '01' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '\n'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '02' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '02' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': '\n'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '03' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '03' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Wall-mount, kitchen sink faucet with swivel spout.'
              },
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '04' + sep +
                                    'technical_drawings' + sep + 'Technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'WATER TAPS' +
                                    sep + '006-Crown' + sep + '04' + sep +
                                   'main_img' + sep + 'img.jpg'),
               'description': 'Dual-control, exposed-wall , bath / shower fitting.'
              },
          ]
        },
    ]
    additional_products = [
        {'name': 'item-001', 'description': 'Oval over counter lavatory',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '001-item' + sep +
                                    'main_img' + sep + 'Over-Counter.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '001-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '001-item' + sep +
                                    'main_img' + sep + 'Over-Counter.jpg'),
               'description': 'Oval over counter lavatory'
              }
          ]
        },
        {'name': 'item-002', 'description': 'Oval over counter lavatory',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '002-item' + sep +
                                    'main_img' + sep + 'Over-Counter.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '002-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '002-item' + sep +
                                    'main_img' + sep + 'Over-Counter.jpg'),
               'description': 'Oval over counter lavatory'
              }
          ]
        },
        {'name': 'item-003', 'description': '70x70, 80x80 cm shower tray made from fine fire clay with floor-rib pattern for safe slip resistance',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '003-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-13-path.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '003-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '003-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-13-path.jpg'),
               'description': '70x70, 80x80 cm shower tray made from fine fire clay with floor-rib pattern for safe slip resistance'
              }
          ]
        },
        {'name': 'item-004', 'description': '70x70, 80x80 cm corner shower tray made from fine fire clay with floor-rib pattern for safe slip resistance',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '004-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-13-path.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '004-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '004-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-13-path.jpg'),
               'description': '70x70, 80x80 cm corner shower tray made from fine fire clay with floor-rib pattern for safe slip resistance'
              }
          ]
        },
        {'name': 'item-005', 'description': 'A unique design of urinals\nincludes an integrated flushing system.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '005-item' + sep +
                                    'main_img' + sep + '1_1.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '005-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '005-item' + sep +
                                    'main_img' + sep + '1_1.jpg'),
               'description': 'A unique design of urinals\nincludes an integrated flushing system.'
              }
          ]
        },
        {'name': 'item-006', 'description': 'Gravena closet',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '006-item' + sep +
                                    'main_img' + sep + 'slibs.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '006-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '006-item' + sep +
                                    'main_img' + sep + 'slibs.jpg'),
               'description': 'Gravena closet'
              }
          ]
        },
        {'name': 'item-007', 'description': 'Lux closet',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '007-item' + sep +
                                    'main_img' + sep + 'Shabah.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '007-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '007-item' + sep +
                                    'main_img' + sep + 'Shabah.jpg'),
               'description': 'Lux closet'
              }
          ]
        },
        {'name': 'item-008', 'description': 'Special closet',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '008-item' + sep +
                                    'main_img' + sep + 'gpr_002.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '008-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '008-item' + sep +
                                    'main_img' + sep + 'gpr_002.jpg'),
               'description': 'Special closet'
              }
          ]
        },
        {'name': 'item-009', 'description': 'Babies floor-standing, water closet available in "s" trap version only with high cistern.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '009-item' + sep +
                                    'main_img' + sep + '216-JAN-path.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '009-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '009-item' + sep +
                                    'main_img' + sep + '216-JAN-path.jpg'),
               'description': 'Babies floor-standing, water closet available in "s" trap version only with high cistern.'
              }
          ]
        },
        {'name': 'item-010', 'description': 'Wall-mounted lavatory for hospitals & people with special needs. Includes one punched & two semi- punched faucet holes.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '010-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-12-path.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '010-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '010-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-12-path.jpg'),
               'description': 'Wall-mounted lavatory for hospitals & people with special needs. Includes one punched & two semi- punched faucet holes.'
              }
          ]
        },
        {'name': 'item-011', 'description': 'Floor-standing, flush valve closet, for hospitals & people with special needs available in "p" & "s" trap versions.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '011-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-14-path.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '011-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '011-item' + sep +
                                    'main_img' + sep + 'A-D-itemes-14-path.jpg'),
               'description': 'Floor-standing, flush valve closet, for hospitals & people with special needs available in "p" & "s" trap versions.'
              }
          ]
        },
        {'name': 'item-012', 'description': 'Wall hung water tank',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '012-item' + sep +
                                    'main_img' + sep + 'wall-hung.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '012-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '012-item' + sep +
                                    'main_img' + sep + 'wall-hung.jpg'),
               'description': 'Wall hung water tank'
              }
          ]
        },
        {'name': 'item-013', 'description': '45,50 and 58 cm lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '013-item' + sep +
                                    'main_img' + sep + '45-Square.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '013-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '013-item' + sep +
                                    'main_img' + sep + '45-Square.jpg'),
               'description': '45,50 and 58 cm lavatory with semi pedestal includes one pre-punched & two semi- punched faucet holes'
              }
          ]
        },
        {'name': 'item-014', 'description': '45 cm and 50 cm lavatory includes one pre-punched & two semi -punched faucet holes.',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '014-item' + sep +
                                    'main_img' + sep + 'Lavatory.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '014-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '014-item' + sep +
                                    'main_img' + sep + 'Lavatory.jpg'),
               'description': '45 cm and 50 cm lavatory includes one pre-punched & two semi -punched faucet holes.'
              }
          ]
        },
        {'name': 'item-015', 'description': '52 cm. lavatory includes one pre-punched & two semi -punched faucet holes',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '015-item' + sep +
                                    'main_img' + sep + '58-Rounded.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '015-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '015-item' + sep +
                                    'main_img' + sep + '58-Rounded.jpg'),
               'description': '52 cm. lavatory includes one pre-punched & two semi -punched faucet holes'
              }
          ]
        },
        {'name': 'item-016', 'description': 'Shell shape lavatory includes one pre-punched faucet hole',
         'main_image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '016-item' + sep +
                                    'main_img' + sep + 'Wadaa.jpg'),
         'parts': [
              {'technical_drawing': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '016-item' + sep +
                                    'technical_drawings' + sep + 'technical.png'),
               'image': os.path.join(str(PRODUCTS_DIR), 'Additional Items' +
                                    sep + '016-item' + sep +
                                    'main_img' + sep + 'Wadaa.jpg'),
               'description': 'Shell shape lavatory includes one pre-punched faucet hole'
              }
          ]
        },
    ]

    cats = {
        'Acrylic Bath Tubs': {'products': acrylic_products},
        'Sanitary Ware': {'products': sanitary_products},
        'Water Taps': {'products': wt_products},
        'Additional Items': { 'products': additional_products}
    }

    for cat, cat_data in cats.items():
        c = Category.objects.get_or_create(name=cat)[0]
        c.slug = slugify(c.name)
        c.save()
        for product in cat_data['products']:
            p = Product.objects.get_or_create(category=c, name=product['name'],
                    description=product['description'],main_image=File(open(product['main_image'], 'rb')))[0]
            p.save()
            for part in product['parts']:
                prt = ProductPart.objects.get_or_create(product=p, description=part['description'],
                    image=File(open(part['image'], 'rb')),
                    technical_drawing=File(open(part['technical_drawing'], 'rb')))[0]
                prt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_products),
    ]
